name: Assign issue to copilot

on:
  issues:
    types: [opened]

jobs:
  check_issue_title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 
      - name: Check Issue Title
        id: check_title
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          if [[ "$ISSUE_TITLE" =~ \[KAN-[0-9]+\] ]]; then
            echo "kanban_issue=true" >> "$GITHUB_OUTPUT"
            echo "Issue title matches the pattern!"
          else
            echo "kanban_issue=false" >> "$GITHUB_OUTPUT"
            echo "Issue title does not match the pattern."
          fi

      - name: Run Actions (if KAN issue)
        if: steps.check_title.outputs.kanban_issue == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Assigning GitHub Copilot to the issue..."
          gh issue edit "${{ github.event.issue.number }}" --add-assignee @copilot
          echo "GitHub Copilot assigned successfully."
          # Add your desired actions here.  For example:
          # - echo "Assigning to project..."
          # - gh project item-add --project "Your Project URL" --issue-number ${{ github.event.issue.number }}
        
